version: "3.7"

x-logging:
  &default-logging
  options:
    max-size: '500m'
    max-file: '5'
  driver: json-file

services:
  # by default exposes sock listed services read only
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    logging: *default-logging
    networks:
      - dockersock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    logging: *default-logging
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Sekurity - if exposing to public one day should at the very least proxy..
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - visualizer

  portainer-agent:
    image: portainer/agent
    logging: *default-logging
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/workspace/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    logging: *default-logging
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    depends_on: 
    - portainer-agent
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - portainer-net
      # traefik.frontend.whiteList.sourceRange: 10.0.0.0/24
      # traefik.frontend.whiteList.useXForwardedFor: ""true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  
  organizr:
    image: organizrtools/organizr-v2
    logging: *default-logging
    environment:
      PUID: 5009
      PGID: 5009
    ports:
      - "9001:80"
    volumes:
      - organizr_config:/config
    networks:
      - portainer-net
      - public
      - dl
      - visualizer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  # volumebackup:
  #   image: osixia/backup
  #   volume: 
  #     - docker_volumes:/data/input:ro
  #     - volumes_backup:/data/backup 
  #   enviornment: 
  #     - BACKUP_CRON_EXP="* * 14 * * "

networks:
  visualizer:
  public:
    external: true
  dl:
    external: true
  portainer-net:
    driver: overlay
    attachable: true
  dockersock:
    external: true

volumes:
  organizr_config:
  portainer_data:
