version: "3.7"
services:
  # by default exposes sock listed services read only
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    networks:
      - dockersock
    environment:
      # CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      # SWARM: 1
      TASKS: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Sekurity - if exposing to public one day should at the very least proxy..
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - visualizer

  redis:
    image: redis
    expose:
      - "6379:6379"
    volumes:
      - mgmt-redis:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - visualizer

  portainer-agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - portainer-net
      # traefik.frontend.whiteList.sourceRange: 10.0.0.0/24
      # traefik.frontend.whiteList.useXForwardedFor: ""true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  visualizer:
  portainer-net:
  dockersock:
    external: true

volumes:
  portainer_data:
  mgmt-redis:
