version: "3.7"
services:
  # by default exposes sock listed services read only
  docker-proxy:
    network_mode: "host"
    image: tecnativa/docker-socket-proxy
    environment:
      # CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      # SWARM: 1
      TASKS: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Sekurity - if exposing to public one day should at the very least proxy..

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - mgmt-redis:/data
    command: redis-server --appendonly yes

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

volumes:
  portainer_data:
  mgmt-redis:
