version: "3.7"

services:
  drone-server:
    image: drone/drone:1.6
    ports:
      - 8000:80
      - 9000:9000
    networks:
      - drone
      - public
    volumes:
      - drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    restart: always
    environment:
      # - DRONE_GITHUB_SKIP_VERIFY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_OPEN=false
      - DRONE_GITHUB=true
    labels:
      traefik.enable: "true"
      traefik.docker.network: "public"
      traefik.backend: "drone"
      traefik.frontend.rule: "Host:drone.ashtonkinslow.com"
      traefik.port: "9000"
      traefik.protocol: "http"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "public"
        traefik.backend: "drone"
        traefik.frontend.rule: "Host:drone.ashtonkinslow.com"
        traefik.port: "9000"
        traefik.protocol: "http"

  drone-agent:
    image: drone/agent:1.6
    command: agent
    restart: always
    depends_on:
      - drone-server
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    environment:
      - DRONE_RPC_SERVER=drone-server:8000

networks:
  public:
    external: true
  drone:
    name: drone_network

volumes:
  drone:
