version: "3.7"

x-logging:
  &default-logging
  options:
    max-size: '500m'
    max-file: '5'
  driver: json-file

services:
  postgres:
    image: postgres:10
    restart: always
    # https://github.com/docker-library/docs/tree/master/postgres#environment-variables=
    logging: *default-logging
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DRONE_PG_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - drone

  drone-server:
    logging: *default-logging
    image: drone/drone:1.6
    # ports:
    #   - 8000:80
    #   - 9000:9000
    networks:
      - drone
      - public
    volumes:
      - drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    restart: always
    environment:
      # - DRONE_GITHUB_SKIP_VERIFY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=false
      - DRONE_OPEN=false
      - DRONE_GITHUB=true
      # - DRONE_LOGS_DEBUG=true
      # - DRONE_LOGS_TRACE=true
      - DRONE_DATABASE_DRIVER=postgres
      - DRONE_DATABASE_DATASOURCE=postgres://postgres:${DRONE_PG_PASS}@postgres:5432/postgres?sslmode=disable # TODO
    labels:
      - "traefik.enable=true"
      # - "traefik.http.middlewares.sslHeaders.headers.SSLHost=drone.ashlab.dev"
      - "traefik.http.routers.drone.rule=Host(`drone.ashlab.dev`)"
      - "traefik.http.routers.drone.middlewares=https_redirect, sslHeaders"
      - "traefik.http.routers.drone.service=drone"
      - "traefik.http.routers.drone.tls=true"
      - "traefik.http.routers.drone.tls.certresolver=le"
      - "traefik.http.services.drone.loadbalancer.server.port=80"
      - "traefik.http.services.drone.loadbalancer.server.scheme=http"
      # - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https" # Standard move to default when traefik fixes behavior
      # - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      # - "traefik.http.middlewares.sslHeaders.headers.framedeny=true"
      # - "traefik.http.middlewares.sslHeaders.headers.sslredirect=true"
      # - "traefik.http.middlewares.sslHeaders.headers.STSSeconds=315360000"
      # - "traefik.http.middlewares.sslHeaders.headers.browserXSSFilter=true"
      # - "traefik.http.middlewares.sslHeaders.headers.contentTypeNosniff=true"
      # - "traefik.http.middlewares.sslHeaders.headers.forceSTSHeader=true"
      # - "traefik.http.middlewares.sslHeaders.headers.STSIncludeSubdomains=true"
      # - "traefik.http.middlewares.sslHeaders.headers.STSPreload=true"
    deploy:
      labels:
        - "traefik.enable=true"
        # - "traefik.http.middlewares.sslHeaders.headers.SSLHost=drone.ashlab.dev"
        - "traefik.http.routers.drone.rule=Host(`drone.ashlab.dev`)"
        - "traefik.http.routers.drone.middlewares=https_redirect, sslHeaders"
        - "traefik.http.routers.drone.service=drone"
        - "traefik.http.routers.drone.tls=true"
        - "traefik.http.routers.drone.tls.certresolver=le"
        - "traefik.http.services.drone.loadbalancer.server.port=80"
        - "traefik.http.services.drone.loadbalancer.server.scheme=http"
        # - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https" # Standard move to default when traefik fixes behavior
        # - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
        # - "traefik.http.middlewares.sslHeaders.headers.framedeny=true"
        # - "traefik.http.middlewares.sslHeaders.headers.sslredirect=true"
        # - "traefik.http.middlewares.sslHeaders.headers.STSSeconds=315360000"
        # - "traefik.http.middlewares.sslHeaders.headers.browserXSSFilter=true"
        # - "traefik.http.middlewares.sslHeaders.headers.contentTypeNosniff=true"
        # - "traefik.http.middlewares.sslHeaders.headers.forceSTSHeader=true"
        # - "traefik.http.middlewares.sslHeaders.headers.STSIncludeSubdomains=true"
        # - "traefik.http.middlewares.sslHeaders.headers.STSPreload=true"

  drone-agent1:
    logging: *default-logging
    image: drone/agent:1.6
    command: agent
    restart: always
    depends_on:
      - drone-server
    # ports:
    #   - 3000:9009
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    environment:
      - DRONE_RUNNER_NAME=derick
      # - DRONE_LOGS_DEBUG=true
      # - DRONE_LOGS_TRACE=true
      - DRONE_RPC_DUMP_HTTP=true
      - DRONE_RPC_DUMP_HTTP_BODY=true
      - DRONE_RPC_SERVER=http://drone-server:80
      # - DRONE_UI_DISABLE=false
      # - DRONE_UI_USERNAME=root
      # - DRONE_UI_PASSWORD=root
      - DRONE_RUNNER_CAPACITY=10

  drone-agent2:
    logging: *default-logging
    image: drone/agent:1.6
    command: agent
    restart: always
    depends_on:
      - drone-server
    # ports:
    #   - 3000:9009
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    environment:
      - DRONE_RUNNER_NAME=bob
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TRACE=true
      - DRONE_RPC_DUMP_HTTP=true
      - DRONE_RPC_DUMP_HTTP_BODY=true
      - DRONE_RPC_SERVER=http://drone-server:80
      # - DRONE_UI_DISABLE=false
      # - DRONE_UI_USERNAME=root
      # - DRONE_UI_PASSWORD=root
      - DRONE_RUNNER_CAPACITY=10

  drone-agent3:
    logging: *default-logging
    image: drone/agent:1.6
    command: agent
    restart: always
    depends_on:
      - drone-server
    # ports:
    #   - 3000:9009
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    environment:
      - DRONE_RUNNER_NAME=james
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TRACE=true
      - DRONE_RPC_DUMP_HTTP=true
      - DRONE_RPC_DUMP_HTTP_BODY=true
      - DRONE_RPC_SERVER=http://drone-server:80
      # - DRONE_UI_DISABLE=false
      # - DRONE_UI_USERNAME=root
      # - DRONE_UI_PASSWORD=root
      - DRONE_RUNNER_CAPACITY=10

networks:
  public:
    external: true
  drone:
    name: drone_network

volumes:
  drone:
  postgres:
