version: "3.7"
services:
  plex:
    network_mode: "host"
    image: linuxserver/plex
    ports:
      - "32400:32400"
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: public
    volumes:
      - /dev/dri:/dev/dri
      - plex_config:/config
      - plex_tv:/data/tvshows #:ro
      - plex_movies:/data/movies #:ro
      - plex_transcode:/transcode
    labels:
      traefik.enable: "true"
      traefik.docker.network: "public"
      traefik.backend: "plex"
      traefik.frontend.rule: "Host:plex.ashtonkinslow.com"
      traefik.port: "32400"
      traefik.protocol: "http"

volumes:
  plex_config_logs: # TODO: readonly based on bind to plex_config/
  plex_config:
  plex_transcode:
  plex_tv: #external
  plex_movies: #external
