version: "3.7"

x-logging: &default-logging
  options:
    max-size: "500m"
    max-file: "5"
  driver: json-file

services:
  plex:
    restart: always
    image: linuxserver/plex
    logging: *default-logging
    ports:
      - target: 32400
        published: 32400
        protocol: tcp
        mode: host
      # - "32400:32400/udp"
      # - "32469:32469"
      # - "32469:32469/udp"
      # - "5353:5353/udp"
      # - "1900:1900/udp"
    networks:
      - public
    environment:
      PUID: 5000
      PGID: 5000
      TZ: America/Chicago
      VERSION: public
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - plex_config:/config
      - plex_tv:/data/tvshows:ro
      - plex_tv4k:/data/tvshows4k:ro
      - plex_movies:/data/movies:ro
      - plex_movies4k:/data/movies4k:ro
      - plex_music:/data/music:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.sslHeaders.headers.SSLHost=plex.ashlab.dev"
      - "traefik.http.routers.plex.rule=Host(`plex.ashlab.dev`)"
      - "traefik.http.routers.plex.middlewares=https_redirect, sslHeaders"
      - "traefik.http.routers.plex.service=plex"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=le"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.services.plex.loadbalancer.server.scheme=http"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https" # Standard move to default when traefik fixes behavior
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.sslHeaders.headers.framedeny=true"
      - "traefik.http.middlewares.sslHeaders.headers.sslredirect=true"
      - "traefik.http.middlewares.sslHeaders.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.sslHeaders.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.sslHeaders.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.sslHeaders.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.sslHeaders.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.sslHeaders.headers.STSPreload=true"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.sslHeaders.headers.SSLHost=plex.ashlab.dev"
        - "traefik.http.routers.plex.rule=Host(`plex.ashlab.dev`)"
        - "traefik.http.routers.plex.middlewares=https_redirect, sslHeaders"
        - "traefik.http.routers.plex.service=plex"
        - "traefik.http.routers.plex.tls=true"
        - "traefik.http.routers.plex.tls.certresolver=le"
        - "traefik.http.services.plex.loadbalancer.server.port=32400"
        - "traefik.http.services.plex.loadbalancer.server.scheme=http"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https" # Standard move to default when traefik fixes behavior
        - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
        - "traefik.http.middlewares.sslHeaders.headers.framedeny=true"
        - "traefik.http.middlewares.sslHeaders.headers.sslredirect=true"
        - "traefik.http.middlewares.sslHeaders.headers.STSSeconds=315360000"
        - "traefik.http.middlewares.sslHeaders.headers.browserXSSFilter=true"
        - "traefik.http.middlewares.sslHeaders.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.sslHeaders.headers.forceSTSHeader=true"
        - "traefik.http.middlewares.sslHeaders.headers.STSIncludeSubdomains=true"
        - "traefik.http.middlewares.sslHeaders.headers.STSPreload=true"

  tautulli:
    restart: always
    image: linuxserver/tautulli:latest
    logging: *default-logging
    environment:
      PUID: 5002
      PGID: 5002
      TZ: America/Chicago
    networks:
      - plex
    volumes:
      - tautulli_config:/config
      - plex_config_logs:/logs
    ports:
      - 8181:8181

  ombi:
    restart: always
    image: linuxserver/ombi:latest
    logging: *default-logging
    environment:
      PUID: 5003
      PGID: 5003
      TZ: America/Chicago
    volumes:
      - ombi_config:/config
    ports:
      - 3579:3579
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.sslHeaders.headers.SSLHost=requests.ashlab.dev"
      - "traefik.http.routers.requests.rule=Host(`requests.ashlab.dev`)"
      - "traefik.http.routers.requests.middlewares=https_redirect, sslHeaders"
      - "traefik.http.routers.requests.service=requests"
      - "traefik.http.routers.requests.tls=true"
      - "traefik.http.routers.requests.tls.certresolver=le"
      - "traefik.http.services.requests.loadbalancer.server.port=3579"
      - "traefik.http.services.requests.loadbalancer.server.scheme=http"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https" # Standard move to default when traefik fixes behavior
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.sslHeaders.headers.framedeny=true"
      - "traefik.http.middlewares.sslHeaders.headers.sslredirect=true"
      - "traefik.http.middlewares.sslHeaders.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.sslHeaders.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.sslHeaders.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.sslHeaders.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.sslHeaders.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.sslHeaders.headers.STSPreload=true"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.sslHeaders.headers.SSLHost=requests.ashlab.dev"
        - "traefik.http.routers.requests.rule=Host(`requests.ashlab.dev`)"
        - "traefik.http.routers.requests.middlewares=https_redirect, sslHeaders"
        - "traefik.http.routers.requests.service=requests"
        - "traefik.http.routers.requests.tls=true"
        - "traefik.http.routers.requests.tls.certresolver=le"
        - "traefik.http.services.requests.loadbalancer.server.port=3579"
        - "traefik.http.services.requests.loadbalancer.server.scheme=http"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https" # Standard move to default when traefik fixes behavior
        - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
        - "traefik.http.middlewares.sslHeaders.headers.framedeny=true"
        - "traefik.http.middlewares.sslHeaders.headers.sslredirect=true"
        - "traefik.http.middlewares.sslHeaders.headers.STSSeconds=315360000"
        - "traefik.http.middlewares.sslHeaders.headers.browserXSSFilter=true"
        - "traefik.http.middlewares.sslHeaders.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.sslHeaders.headers.forceSTSHeader=true"
        - "traefik.http.middlewares.sslHeaders.headers.STSIncludeSubdomains=true"
        - "traefik.http.middlewares.sslHeaders.headers.STSPreload=true"

networks:
  public:
    external: true
  plex:

volumes:
  ombi_config:
  tautulli_config:

  plex_tv:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/lutece/media/tv/"

  plex_tv4k:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/lutece/media/tv4k/"

  plex_movies:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/lutece/media/movies/"

  plex_movies4k:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/lutece/media/movies4k/"

  plex_music:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/lutece/media/music/"

  plex_config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,rw"
      device: "/mnt/workspace/plex/"

  plex_config_logs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/mnt/workspace/plex/Library/Application Support/Plex Media Server/Logs/"
