version: "3.7"
services:

  cloudflare-ddns:
    image: joshava/cloudflare-ddns
    networks: 
      - cfddns
    environment:
      ZONE: ashtonkinslow.com
      HOST: ddns.ashtonkinslow.com
      EMAIL: cloudflare@ashtonkinslow.com
      API: ${CF_API_KEY}
      TTL: 120
      PROXY: "false"
      FORCE_CREATE: "true"

  traefik:
    ports:
      - "80:80"
      - "443:443"
      - "8181:8080"
    image: traefik:latest
    networks:
      - public
      - dockersock
    command:
      # - "--debug=true" # sekurity check
      # - "--api" # sekurity check exposes config via 8080
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.email=acme@ashtonkinslow.com"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      # - "--acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory" # lets encrypt staging, remove after verified deployment
      - "--acme.tlsChallenge"
      - "--acme.onHostRule=true"
      - "--docker"
      - "--docker.endpoint=tcp://mgmt_docker-proxy:2375" ## references mgmt stack
      # - "--docker.exposedbydefault=false" # sekurity check
      - "--docker.swarmMode"
      - "--docker.domain=mydomain.ca"
      - "--docker.watch"

networks:
  public:
    external: true
  dockersock: 
    external: true
  cfddns: 