version: "3.7"

x-logging: &default-logging
  options:
    max-size: "500m"
    max-file: "5"
  driver: json-file

services:
  cloudflare-ddns:
    image: joshava/cloudflare-ddns
    logging: *default-logging
    networks:
      - cfddns
    environment:
      ZONE: ashlab.dev
      HOST: ddns.ashlab.dev
      EMAIL: cloudflare@ashlab.dev
      API: ${CF_API_KEY}
      TTL: 120
      PROXY: "false"
      FORCE_CREATE: "true"

  traefik:
    ports:
      - "80:80"
      - "443:443"
      - "8183:8080"
    image: traefik:1.7
    logging: *default-logging
    volumes:
      - traefik_certs:/certs
    networks:
      - public
      - dockersock
    command:
      # - "--debug=true" # sekurity check
      # - "--api" # sekurity check exposes config via 8080
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.email=acme@ashlab.dev"
      - "--acme.storage=/certs/acme.json"
      - "--acme.entryPoint=https"
      # - "--acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory" # lets encrypt staging, remove after verified deployment
      - "--acme.tlsChallenge"
      - "--acme.onHostRule=true"
      - "--docker"
      - "--docker.endpoint=tcp://mgmt_docker-proxy:2375" ## references mgmt stack
      # - "--docker.exposedbydefault=false" # sekurity check
      # - "--docker.swarmMode"
      # - "--docker.domain=mydomain.ca"
      - "--docker.watch"
      - "--insecureSkipVerify=true"

networks:
  public:
    external: true
  dockersock:
    external: true
  cfddns:

volumes:
  traefik_certs:
