version: "3.7"

x-logging: &default-logging
  options:
    max-size: "500m"
    max-file: "5"
  driver: json-file

services:
  db:
    image: mariadb
    logging: *default-logging
    networks:
      - nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${NC_DB_ROOT_PASS}
      MYSQL_PASSWORD: ${NC_DB_PASS}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  redis:
    image: redis
    logging: *default-logging
    volumes:
      - redis:/data
    networks:
      - nextcloud

  nextcloud:
    image: nextcloud:apache
    logging: *default-logging
    volumes:
      - nextcloud:/var/www/html
      - nexctcloud_config:/var/www/html/config
      - nexctcloud_custom_apps:/var/www/html/custom_apps
      - nextcloud_data:/data
      - nextcloud_tv:/tv:ro
      - nextcloud_tv4k:/tv:ro
      - nextcloud_movies:/movies:ro
      - nextcloud_movies4k:/movies4k:ro
      - nextcloud_music:/music:ro
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: ${NC_DB_PASS}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.ashtonkinslow.com
      REDIS_HOST: redis
      NEXTCLOUD_DATA_DIR: /data
    depends_on:
      - db
      - redis
    networks:
      - nextcloud
      - public
    # labels:
    #   traefik.enable: "true"
    #   traefik.docker.network: "public"
    #   traefik.backend: "nextcloud"
    #   traefik.frontend.rule: "Host:nextcloud.ashtonkinslow.com"
    #   traefik.port: "80"
    #   traefik.protocol: "http"
    # user: "5001:5001"
    # deploy:
    #   labels:
    #     traefik.enable: "true"
    #     traefik.docker.network: "public"
    #     traefik.backend: "nextcloud"
    #     traefik.frontend.rule: "Host:nextcloud.ashtonkinslow.com"
    #     traefik.port: "80"
    #     traefik.protocol: "http"
    # traefik.frontend.whiteList.sourceRange: 10.0.0.1/24
    # traefik.frontend.whiteList.useXForwardedFor: "true"

  nextcloud-cron:
    image: nextcloud:apache
    logging: *default-logging
    restart: always
    networks:
      - nextcloud
    volumes:
      - nextcloud:/var/www/html
      - nexctcloud_config:/var/www/html/config
      - nexctcloud_custom_apps:/var/www/html/custom_apps
    user: "5001:5001"
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    deploy:

networks:
  nextcloud:
    driver: overlay
  public:
    external: true

volumes:
  redis:
  db:
  nextcloud:
  nexctcloud_config:
  nexctcloud_custom_apps:
  nextcloud_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,rw"
      device: "/lutece/apps/nextcloud/"

  nextcloud_tv:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/lutece/media/tv/"

  nextcloud_tv4k:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/lutece/media/tv4k/"

  nextcloud_movies:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/lutece/media/movies/"

  nextcloud_movies4k:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/lutece/media/movies4k/"

  nextcloud_music:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,ro"
      device: "/lutece/media/music/"
