version: "3.7"

services:
  db:
    image: mariadb
    networks:
      - nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${NC_DB_ROOT_PASS}
      MYSQL_PASSWORD: ${NC_DB_PASS}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  redis:
    image: redis
    volumes:
      - redis:/data
    networks:
      - nextcloud

  nextcloud:
    image: nextcloud:apache
    volumes:
      - nextcloud:/var/www/html
    environment:
      MYSQL_PASSWORD: ${NC_DB_PASS}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.ashtonkinslow.com
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    networks:
      - nextcloud
      - public
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "public"
        traefik.backend: "nextcloud"
        traefik.frontend.rule: "Host:nextcloud.ashtonkinslow.com"
        traefik.port: "80"
        traefik.protocol: "http"
        traefik.frontend.whiteList.sourceRange: 10.0.0.0/24
        traefik.frontend.whiteList.useXForwardedFor: "true"

  nextcloud-cron:
    image: nextcloud:fpm-alpine
    networks:
      - nextcloud
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

networks:
  nextcloud:
  public:
    external: true

volumes:
  redis:
  db:
  nextcloud:
